### ISSUE TITLE
Could not find a declaration file for module 'lighthouse/lighthouse-core'. 

### ISSUE THREAD

**Issue by DJ-Glock** [AndrejsAbrickis/lighthouse-azure-devops#1]
Hello @AndrejsAbrickis 
I'm trying to use your example, but face the following error:
![image](https://user-images.githubusercontent.com/26511191/63764653-f7a3bf80-c8cf-11e9-87db-0bf989182283.png)

In the same time if I run it, it works. Probably I need to ask this question to lighthouse developers...

**Comment by AndrejsAbrickis** [comment]
@DJ-Glock this is interesting as I cannot reproduce this issue. What's your typescript's version? Have you modified the tsconfig.json? Have you opened the `lighthouse-azure-devops` directory in the code or a higher directory? 

These are just hints because it's hard to tell what's the based on the screenshot.

**Comment by DJ-Glock** [comment]
@AndrejsAbrickis ah, I did not mention that I just used your code in my project. Apologies.
Let me try to open your project.

**Comment by DJ-Glock** [comment]
Okay, so I've just downloaded your project, opened lighthouse-azure-devops-mster folder it in the Visual Studio Code.
Run yarn to install all dependencies and see the same:
![image](https://user-images.githubusercontent.com/26511191/63767888-7bad7580-c8d7-11e9-9a7f-ddbfd5511836.png)

TypeScript version: 3.5.2


Visual Studio Code
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Looks like I have to go the way described here:
https://medium.com/@chris_72272/migrating-to-typescript-write-a-declaration-file-for-a-third-party-npm-module-b1f75808ed2

**Comment by AndrejsAbrickis** [comment]
This is still interesting. But the only difference I see is the OS version, I've tested this only on MacOS. Have to test it also on Win.
